#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

echo "virtualenv"
virtualenv --no-site-packages --distribute --clear ${OPENSHIFT_DATA_DIR}/${OPENSHIFT_APP_NAME}
echo "Sourcing environment"
source ${OPENSHIFT_DATA_DIR}/${OPENSHIFT_APP_NAME}/bin/activate

export PIP_DOWNLOAD_CACHE=${OPENSHIFT_TMP_DIR}/.pip/cache
pip install --log=${OPENSHIFT_TMP_DIR}/.pip/pip.log -r ${OPENSHIFT_REPO_DIR}/requirements.txt

