#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
echo "Entering VirtualEnv"
source ${OPENSHIFT_DATA_DIR}venv/bin/activate

echo "syncdb --noinput"
python ${OPENSHIFT_REPO_DIR}manage.py syncdb --noinput

echo "collectstatic --noinput"
python ${OPENSHIFT_REPO_DIR}manage.py collectstatic --noinput
