#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
echo "Sourcing environment"
source ${OPENSHIFT_DATA_DIR}/${OPENSHIFT_APP_NAME}/bin/activate

echo "Preparing Database"
echo -e 'import hb.settings\nprint hb.settings.DATABASES'|python ${OPENSHIFT_REPO_DIR}/manage.py shell
echo "syncdb --noinput"
python ${OPENSHIFT_REPO_DIR}/manage.py syncdb --noinput

echo "collectstatic --noinput"
python ${OPENSHIFT_REPO_DIR}/manage.py collectstatic --noinput
