#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

echo "Entering VirtualEnv"
source ${OPENSHIFT_DATA_DIR}venv/bin/activate

GUNICORN_BIN="python ${OPENSHIFT_REPO_DIR}manage.py run_gunicorn"
LOGFILE=${OPENSHIFT_LOG_DIR}gunicorn_out.log
ACCESS_LOGFILE=${OPENSHIFT_LOG_DIR}gunicorn_access.log
PIDFILE=${OPENSHIFT_DATA_DIR}gunicorn.pid

echo "Starting gunicorn"
$GUNICORN_BIN $OPENSHIFT_INTERNAL_IP:$OPENSHIFT_INTERNAL_PORT \
    --daemon \
    --pid=$PIDFILE \
    --log-file=$LOGFILE \
    --access-logfile=$ACCESS_LOGFILE \
    --log-level=info
